import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/auth-provider";
import { MunicipalityProvider } from "@/providers/municipality-provider";
import { UsersProvider } from "@/providers/user-provider";
import { SupervisorProvider } from "@/providers/supervisor-provider";
import { VehicleProvider } from "@/providers/vehicle-provider";
import { DriverProvider } from "@/providers/driver-provider";
import { MechanicProvider } from "@/providers/mechanic-provider";
import { IncidentProvider } from "@/providers/incident-provider";
import { App } from "antd/es";
import { JobCardProvider } from "@/providers/jobCard-provider";

export const metadata: Metadata = {
  title: "DriveOps: Fleet Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <App>
          <JobCardProvider>
            <IncidentProvider>
              <MechanicProvider>
                <DriverProvider>
                  <VehicleProvider>
                    <SupervisorProvider>
                      <MunicipalityProvider>
                        <UsersProvider>
                          <AuthProvider>
                            {children}
                          </AuthProvider>
                        </UsersProvider>
                      </MunicipalityProvider>
                    </SupervisorProvider>
                  </VehicleProvider>
                </DriverProvider>
              </MechanicProvider>
            </IncidentProvider>
          </JobCardProvider>
        </App>
      </body>
    </html>
  );
}
