import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/auth-provider";
import { MunicipalityProvider } from "@/providers/municipality-provider";
import { UsersProvider } from "@/providers/user-provider";
import { SupervisorProvider } from "@/providers/supervisor-provider";
import { VehicleProvider } from "@/providers/vehicle-provider";
import { DriverProvider } from "@/providers/driver-provider";
import { MechanicProvider } from "@/providers/mechanic-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MechanicProvider>
          <DriverProvider>
            <VehicleProvider>
              <SupervisorProvider>
                <MunicipalityProvider>
                  <UsersProvider>
                    <AuthProvider>
                      {children}
                    </AuthProvider>
                  </UsersProvider>
                </MunicipalityProvider>
              </SupervisorProvider>
            </VehicleProvider>
          </DriverProvider>
        </MechanicProvider>
      </body>
    </html>
  );
}
